# Here are the server configs

Data:
  spawn: []
  prefix: '&f&lMoti&a&lMaa &8&l»&7'
  permission-prefix: onecore.
  baltop-update-interval: 5
  # How player & server data is saved. Baltop also updates after database is updated.
  data-save-interval-minutes: 5
  kicked-for-spamming-bypass: kick.bypass
  user-console-filter: true
  mentions-enabled: true
  chat:
    color-permission: chat.colors
    colors-enabled: true
    formatter-enabled: true
    # {0} = player & {1} = message and PlaceholderAPI support if installed. Dont use %s!
    format: '%vault_prefix%{0}&f: {1}'
  sign:
    color-permission: sign.colors
    shift-edit-permission: sign.edit
    shift-edit-enabled: true
  teleport:
    cooldown-bypass-permission: teleport.bypass
    delay: 3
    expire: 10
  # If true it resets velocity on command & plugin teleports
    velocity-reset: true
    with-vehicle-permission: teleport.withvehicle
  economy:
    # Minutes
    baltop-update-interval: 5
    currency-plural: €
    currency-singular: €
    enabled: false
    use-oneeconomy: false
    start-money: 500
  backups:
    #broken atm
    stats-enabled: false
    playerdata-enabled: true
    database-enabled: true
