# Here are the server configs

Data:
  spawn: []
  prefix: '&f&lMoti&a&lMaa &8&l»&7'
  # This prefix will be infront of all onecore permissions.
  permission-prefix: moticore.
  # How player & server data is saved. Baltop also updates after database is updated.
  data-save-interval-minutes: 5
  kicked-for-spamming-bypass: kick.bypass
  user-console-filter: true
  mentions:
    enabled: true
    # Color of the mention
    color: '<#00ff00>&l'
    # Permission to mention players
    permission: mention
    # Permission to mention everyone
    mention-everyone-permission: mention-everyone
    # Sound to play when mentioned
    sound: BLOCK_NOTE_BLOCK_BANJO
  chat:
    colors-enabled: true
    color-permission: chat.colors
    formatter-enabled: true
    # To use PlaceholderAPI use {<papi_placeholder>} and make sure you have installed
    # right papi expansions with /papi ecloud download <expansion>.
    # If you want to use % in the format use %% instead.
    # {0} = player
    # {1} = message
    # {vault_prefix} = Example papi placeholder for vault prefix. (/papi ecloud download vault)
    format: '{vault_prefix}{0}&f: {1}'
    # If placeholder is empty it causes double spacing. This fixes it.
    remove-doublespaces: true
    # Removes whitespaces from start & end of message
    trim: true
  sign:
    color-permission: sign.colors
    shift-edit-enabled: true
    shift-edit-permission: sign.edit
  teleport:
    cooldown-bypass-permission: teleport.bypass
    delay: 3
    expire: 30
    # If true it resets velocity on command & plugin teleports
    velocity-reset: true
    with-vehicle-permission: teleport.withvehicle
    force-spawn-on-join: false
  economy:
    # Minutes
    baltop-update-interval: 5
    currency-plural: €
    currency-singular: €
    enabled-hook: false
    use-oneeconomy: false
    start-money: 500
  backups:
    #broken atm
    stats-enabled: false
    playerdata-enabled: true
    database-enabled: true
