# Here are the server configs

Data:
  spawn: []
  prefix: '&9&lOnecore &8&l»&7'
  back-history-size: 10
  chat-color-permission: chat.colors
  chat-colors-enabled: true
  # How player & server data is saved. Baltop also updates after database is updated.
  data-save-interval-minutes: 5
  kicked-for-spamming-bypass: kick.bypass
  permission-prefix: onecore.
  sign-color-permission: sign.colors
  sign-shift-edit-permission: sign.edit
  sign-shift-edit-enabled: true
  teleport-delay: 3
  teleport-expire: 10
  # If true it resets velocity on command & plugin teleports
  telepor-velocity-reset: true
  teleport-with-vehicle: true
  user-console-filter: true
  mentions-enabled: true
  economy:
    currency-plural: €
    currency-singular: €
    enabled: true
    use-oneeconomy: true
    start-money: 500
  backups:
    #broken atm
    stats-enabled: false
    playerdata-enabled: true
    database-enabled: true
