# Here are the server configs

Data:
  spawn: []
  prefix: '&9&lOnecore &8&l»&7'
  back-history-size: 10
  baltop-update-interval: 60
  chat-color-permission: chat.colors
  chat-colors-enabled: true
  # How player & server data is saved. Baltop also updates after database is updated.
  data-save-interval-minutes: 5
  kicked-for-spamming-bypass: kick.bypass
  permission-prefix: onecore.
  sign-color-permission: sign.colors
  sign-shift-edit-permission: sign.edit
  sign-shift-edit-enabled: true
  teleport-delay: 3
  teleport-expire: 10
  # If true it resets velocity on command & plugin teleports
  telepor-velocity-reset: true
  teleport-with-vehicle: true
  user-console-filter: true
  mentions-enabled: true
  rtp:
    #todo rtp-cooldown-seconds: 60
    radius: 10000
    # How often player can be queued to rtp
    # Example if its 20 ticks and 100 players do rtp same time it will take
    # 20 ticks * 100 players = 2000 ticks = 100 seconds
    # so the time taken for some player to rtp + queuetick = when next player starts process
    # use 1 or above
    queue-tick: 20
    # How often new random location can be scanned per player (milliseconds)
    delay-between-location-scan: 100
    # How many times it tries to find new location
    scans-till-time-out: 5
  economy:
    currency-plural: €
    currency-singular: €
    enabled: true
    use-oneeconomy: true
    start-money: 500
  backups:
    stats-enabled: true
    playerdata-enabled: true
    database-enabled: true
