name: Development Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  development_build:
    name: Build dev jars
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get project version
        id: get_version
        run: echo "::set-output name=version::$(xmllint --xpath '/*[local-name()="project"]/*[local-name()="version"]/text()' pom.xml)"
      - name: Print project version
        run: echo "Project version is ${{ steps.get_version.outputs.version }}"
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'
      - name: Build with Maven
        run: |
         mvn package
          git_hash=$(git rev-parse --short "$GITHUB_SHA")
          echo "git_hash=$git_hash" >> $GITHUB_ENV
          echo "snapshotVersion=5.5-SNAPSHOT" >> $GITHUB_ENV
          echo "artifactPath=$(pwd)/builds" >> $GITHUB_ENV
      - name: Upload Plugin jar
        uses: actions/upload-artifact@v3
        with:
          name: MotiCore-${{ steps.get_version.outputs.version }}.jar
          path: ${{ env.artifactPath }}/MotiCore-${{ env.GITHUB_RUN_NUMBER }}.jar
          
          
          
          
          
          
          
          
         
